# Site settings
title: Yeoh Family Handbook
description: A comprehensive guide and documentation for the Yeoh family
baseurl: "/yeoh-handbook" # the subpath of your site
url: "https://wyred.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
nav_links:
  - title: Home
    url: /
  - title: Family History
    url: /family-history/
    children:
      - title: Timeline
        url: /family-history/timeline/
      - title: Family Tree
        url: /family-history/tree/
      - title: Notable Members
        url: /family-history/members/
  - title: Traditions
    url: /traditions/
    children:
      - title: Celebrations
        url: /traditions/celebrations/
      - title: Customs
        url: /traditions/customs/
  - title: Recipes
    url: /recipes/
    children:
      - title: Main Dishes
        url: /recipes/main-dishes/
      - title: Desserts
        url: /recipes/desserts/
      - title: Soups
        url: /recipes/soups/
      - title: Tea & Beverages
        url: /recipes/beverages/
  - title: Photos
    url: /photos/
  - title: About
    url: /about/

# Collections
collections:
  family:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/